### ISSUE TITLE
I have Error from Compilation and Run

### ISSUE THREAD

**Issue by Legun** [runuo/runuo#13]
Compilation
-----------------------------------------------------------------
dmcs -optimize+ -unsafe -t:exe -out:RunUO.exe -win32icon:Server/runuo.ico -nowarn:219,414 -d:MONO -recurse:Server/*.cs
warning CS8001: SDK path could not be resolved
Server/TileMatrix.cs(445,36): warning CS0618: `System.IO.FileStream.Handle' is obsolete: `Use SafeFileHandle instead'
Server/TileMatrix.cs(524,31): warning CS0618: `System.IO.FileStream.Handle' is obsolete: `Use SafeFileHandle instead'
Server/TileMatrixPatch.cs(109,34): warning CS0618: `System.IO.FileStream.Handle' is obsolete: `Use SafeFileHandle instead'
Server/TileMatrixPatch.cs(179,35): warning CS0618: `System.IO.FileStream.Handle' is obsolete: `Use SafeFileHandle instead'
Compilation succeeded - 5 warning(s)
===================================================================

Run
------------------------------------------------------------------------
mono RunUO.exe
RunUO - [https://github.com/runuo/] Version 2.5.0.35154
Core: Running on .NET Framework Version 4.0.30319
Core: Optimizing for 4 64-bit processors
Core: Unix environment detected
RandomImpl: CSPRandom (Software)
Scripts: Compiling C# scripts...ScriptCompiler: CS0006: Metadata file `System.Web.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Data.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Drawing.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Windows.Forms.dll' could not be found
done (0 errors, 0 warnings)
Scripts: One or more scripts failed to compile or no script files were found.
 - Press return to exit, or R to try again.

I Use LinuxMint 17.2 ( Ubuntu 14.04.3)

**Comment by Vorspire** [comment]
Try adding 618 to -nowarn like this; 

-nowarn:219,414,618

**Comment by Legun** [comment]
no
Server/Utility.cs(616,25): warning CS1635: Cannot restore warning `CS0618' because it was disabled globally
Server/Utility.cs(623,25): warning CS1635: Cannot restore warning `CS0618' because it was disabled globally

Scripts: Compiling C# scripts...ScriptCompiler: CS0006: Metadata file `System.Web.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Data.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Drawing.dll' could not be found
ScriptCompiler: CS0006: Metadata file `System.Windows.Forms.dll' could not be found

But on Windows 7 its Run OK

**Comment by Derrick-** [comment]
If this was Windows, I would ask if you have the full .Net framework installed.

Any chance you have a partial .Net 4.0 installation in Mono (like "Client Profile" in Windows)?

**Comment by msturgill** [comment]
Many Linux distributions have the System.Drawing.dll assembly in a separate package. The last time I looked on a Debian based distribution, the package was "libmono-winforms2.0-cil".

Install this package and try again.

**Comment by sithUO** [comment]
Currently (on Debian unstable, at least) that assembly lives in **libmono-system-drawing4.0-cil**, which should be pulled in if the user installs mono-complete.  I have the same error when compiling with dmcs (which is officially deprecated [0] though it still exists).  Additionally, attempting to run the server results in immediate core dump.

I suspect what's happening is that @Legun has a similar setup to what I have (sid+mono-complete), wherein all the assemblies live under */usr/lib/mono/4.5/* and as a result dmcs can't find the requisite assembly under *4.0/*.  According to the man page[1], mcs defaults to the latest SDK anyways.

[0] - http://www.mono-project.com/docs/about-mono/languages/csharp/
[1] - http://linux.die.net/man/1/mcs
