### ISSUE TITLE
Trading currency with secure trade window

### ISSUE THREAD

**Issue by Hjornskar** [runuo/runuo#18]
While testing trading large amounts of currency, I noticed a small inconsistency when trading amounts that will result in conversions between gold and platinum. An example:

Player1 starts with 7 platinum and 0 gold, Player2 starts with 8 platinum and 0 gold.
Player1 trades 1 platinum and 100,000,000 gold.
Player2 received 1 platinum and 99,999,999 gold.
Player1 balance was correct at 5 platinum and 900,000,000 gold
Player2 balance was 9 platinum and 99,999,999 gold.

Player1 adds a bank check for 100,000,000 gold to even the balance.
Player1 new balance was 6 platinum and 0 gold.

Player2 adds a bank check for 900,000,001 gold to even the balance.
Player2 new balance was 10 platinum and 1 gold.

Somewhere along the way this 1 gold inconsistency is appearing. Checking the Account.TotalPlat and Account.TotalGold, the values are consistent with the numbers listed above, so likely there's a problem somewhere in the conversions.

Edit:
As another data point, I tried the same currency trading scenario as above with ServUO and did not experience the 1 gold inconsistency.

**Comment by kamronbatman** [comment]
I think the issue might be that TotalCurrency on the account is a double.  I noticed in several places Math.Truncate is used, and if the TotalCurrency is close to, but not exactly what it should be, then the truncation may make it look like it has 1 less gold.

I wonder if there is a reason we cannot use a ulong instead of a double too.

**Comment by kamronbatman** [comment]
I replicated the issue actually:
https://repl.it/ERd9/1

**Comment by kamronbatman** [comment]
Here is an example of how to fix it by converting all of the double representations to decimals.
https://repl.it/ERd9/2

**Comment by kamronbatman** [comment]
Why is this being closed? This needs fixing.
