### ISSUE TITLE
PacketWriter Pool Contains check, why is this needed?

### ISSUE THREAD

**Issue by paezao** [runuo/runuo#23]
Hello,

https://github.com/runuo/runuo/blob/master/Server/Network/PacketWriter.cs#L69

Why is this check needed?

**Comment by msturgill** [comment]
This check is to ensure a released instance isn't placed into the free pool multiple times. If this occurs, future consumers could receive a reference to the same instance..

I don't know if there was a specific scenario that caused us to be concerned about this or if it was a preemptive safety measure (or a general debugging addition).
