### ISSUE TITLE
CompileAssemblyFromFile raises exception on mono 5.4.0.201 on Debian Linux

### ISSUE THREAD

**Issue by Ugdhar** [runuo/runuo#36]
https://github.com/runuo/runuo/blob/5e7de85760e7ec84ad8e3f68e7c28ed4fccca3e4/Server/ScriptCompiler.cs#L238

The call to CompileAssemblyFromFile causes an exception for the empty path using mono 5.4.0.201 on debian 8. Using the packages from mono-project.com's suggested install method for debian.

Replacing the empty quotes with the files variable as per the windows compile code seemed to fix it. Honestly not sure what changed that broke it, I imagine something in the way the mono script compiler works?

**Comment by kamronbatman** [comment]
I am having trouble getting it to compile with or without the changes on Mac using Mono 5.4 and 5.8.
