### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ghost** [runuo/runuo#37]
There haven't been any commits for 4 months now. Is this dead?

**Comment by IcculusC** [comment]
think so, but there are people with existing projects based on runuo, and plenty more with knowledge

**Comment by kamronbatman** [comment]
I think the main Repo is dead.  But there are definitely people (like @IcculusC and me) who still have big ideas to improve RunUO.  It is a matter of getting a good healthy set of devs to move forward.

**Comment by msturgill** [comment]
There is no active development on this repository but there are a few maintainers that review pull requests.
