### ISSUE TITLE
Is NEWTIMERS used? How should it be used?

### ISSUE THREAD

**Issue by kamronbatman** [runuo/runuo#39]
@msturgill, I noticed you added a NEWTIMERS option/preprocessor directive, but I don't see it used.
Is this something for devs to use in their scripts as needed? Is it possible to get an example if this is the case?

https://github.com/runuo/runuo/blob/d038571b412188c2f4416f29846f11275c1e7bcb/Server/ScriptCompiler.cs#L95

**Comment by msturgill** [comment]
These were only added for third party script compatibility.

**Comment by kamronbatman** [comment]
Thanks!
