### ISSUE TITLE
Covetous - Wrong Teleport Locations

### ISSUE THREAD

**Issue by TestoTestov** [runuo/runuo#4]
I think that the teleporters locations in Covetous dungeon level 3 to Lake Cave and Covetous dungeon level 3 to Torture Chambers are wrong (Felucca/Trammel). The teleporters don't teleport me from level 3 to Lake Cave and to Torture Chambers. I move teleporters one step up (from teleport location coordinates X:5594 Y:1840 Z:-9 to coordinates X:5594 Y:1840 Z:-8 from Level 3 to Lake Cave) then teleport work for me. I try this for RunUO 2.3 and 2.5.

**Comment by Nerun** [comment]
Thank you very much. Both entrances (to Lake Cave and Torture Chambers) was fixed in Distro 144. Additionaly, Nerun's Distro was never supported by RunUO team or even Mark Sturgill, but by me. So, please post issues in https://code.google.com/p/runuo-nerun-distro/issues/list.
