### ISSUE TITLE
Bump to .NET Framework 4.6, Mono 5 & C# 7

### ISSUE THREAD

**Issue by kamronbatman** [runuo/runuo#40]
So it looks like Mono 5 supports everything up to C# 7 and is fairly stable. Also .NET Framework 4.6-4.7.1 is supported by Windows 7/2008 R2+.

Thoughts on bumping the base framework to at least .NET Framework 4.6 and Mono 5.0 (Rosyln) so we can use C# 7 features, specifically the Async/Threading stuff?

**Comment by Vorspire** [comment]
This can be done on a per-project basis at your discretion by modifying the build options in Visual Studio and editing the Compile bat files in the root directory.
