### ISSUE TITLE
New shard support

### ISSUE THREAD

**Issue by thehaunted88** [runuo/runuo#43]
Hi,

I’m new to coding I’m not new to computers and have a basic understanding of what I’m doing. Just would really appreciate a few tips and advice,

I want to set up my own UO Shard. Obviously I understand it’s not going to happen overnight but I’ve got to start somewhere right lol!

So I managed to get RUNUO to work with Visual Studio. Managed to get latest version running.

I created a admin account and played around for a few minutes trying different things out and managed to log in using the local IP address with razor I’ve used uo steam before as well not sure which is best?

I noticed that when I quit visual studio and loaded it back up i lost the shard and had to re-create the admin account and the server was wiped. Am I missing something here? Do I need to save the progress before I exit and where can I save a back up if I want to pay for someone to host the shard for me?

How do I get my friend to connect? Obviously I need a IP for him to use razor to connect to can I find this listed in visual studio somewhere?

How do I change the name of the shard?

Can anyone recommend a free website I could use to put details of the server on? Might just keep a Facebook page for the time being until I decide to pay out for a domain good idea? I’m not going to make the shard public for a year or so until I can finish it.

I worked out most things like [add banker for adding an NPC banker

Are there any other useful ones that are not listed when you log in on the shortlist?

Thanks a lot and really appreciate any support and advice!

**Comment by thehaunted88** [comment]
So managed to find on [admin there’s an option to create worlds which starts adding in moongates, doors etc but it crash’s at decoration? And kicks me out of server

**Comment by thehaunted88** [comment]
Also is there a way to ge the server to auto create accounts? Will it just do this automatically?

**Comment by Vorspire** [comment]
Please visit http://www.servuo.com for an up-to-date UO emulator and active community support.
