### ISSUE TITLE
What happened RunUO ??

### ISSUE THREAD

**Issue by jedininja28** [runuo/runuo#46]
hey, i spent bunch of time a few months ago trying to post all the scripts iv made but the runuo site kept blocking me and lagging out, UOGamers has all but disappeared and is trying to move people toward serve uo? um, no. so whats up? 

Is it a local issue here, or is EA up your @$$, the cops, ddos, hackers, lack of traffic, what is it? i don't for moment believe that Hybrid or Demise just up and vanished. there were alot of old dedicated players on both servers, iv been trying to get GM on both forever. if you need help ill do what i can, runuo is the only reason i took interest in C#, i learned C# offline with RUO's help files, crash reports and compiling errors. Meia is loyal as fuk... i suppose the other half of my uog Friends would know me as Azaroth or Oblivion.

anyways, i made a lot of cool lootpacks, and mobs, i just need someplace to post it. my server was stolen last year and i had to completely rewrite everything form scratch on crappy library computers. is there a place here on github to post such things or a forum maybe? 

thanks for your work.

**Comment by kamronbatman** [comment]
There is runuo.net but essentially the community is dead.
I am also building a successor to RunUO using modern technology and techniques with a focus on performance and stability.
[ModernUO](GitHub.com/ModernUO/ModernUO)
If interested check it out and click the discord link to be a part of the (currently small) community.

**Comment by jedininja28** [comment]
You link there took me to an error page. 
https://github.com/runuo/runuo/issues/GitHub.com/ModernUO/ModernUO

**Comment by kamronbatman** [comment]
Fixed it.

**Comment by jedininja28** [comment]
Nope, still the error page. Im useing a treasonbox one though. Err xbox.

**Comment by Ugdhar** [comment]
servuo.com is pretty active

**Comment by kamronbatman** [comment]
@jedininja28, when I said I fixed it, I meant I fixed that ModernUO link. It works and I see you found it.
I welcome everyone to head to ModernUO as we build the successor to RunUO together as a community.

**Comment by kamronbatman** [comment]
Someone needs access to merge them. And the people that have access to merge PRs are working on ServUO.

**Comment by Derrick-** [comment]
I can merge

**Comment by kamronbatman** [comment]
The timer wheel should be replaced with libuv. I don't recommend merging it per @jaedan.

**Comment by kamronbatman** [comment]
@Derrick-, I forgot to mention that .NET Core doesn't support hot compilation. It is also not that great of a feature. There is much more flexibility in drop-in already-compiled assemblies. It is also much faster.
ModernUO can be published and booted in less than 9 seconds.
