### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by ekaterinanikiforova** [runuo/runuo#47]
Hello,
I checked RunUO with a PVS-Studio static analyzer and found several suspicious places in the code. The most interesting places in my opinion I described in the article: "[RunUO Check by the PVS-Studio Analyzer](https://www.viva64.com/en/b/0711/)". Not all of the analyzer's warnings were cited in the article. Perhaps some warnings not considered in the article will seem more interesting than the ones, described by me :) Therefore, I suggest trying the [license for open-source projects](https://www.viva64.com/en/b/0614/) and check the project yourself. Hopefully this will help you make the code even better.

**Comment by kamronbatman** [comment]
Thank you for going through this! Unfortunately RunUO is dead. Lots of these were in fixed in ServUO.

I tried to fix lots of these as part of the [ModernUO](https://github.com/modernuo/modernuo)  project using Rider. I would love a static analysis and a PR for ModernUO to catch the rest of them.
