### ISSUE TITLE
Add "topics" to "about" section in GitHub

### ISSUE THREAD

**Issue by Nerun** [runuo/runuo#49]
I know RunUO is dead and ServUO is the current, but woul be goo to add the **topics** bellow to thesection **About** of GitHub. Click the gear, and under topics add:
- gpl
- gplv2
- runuo
- ultima online
- uo

gpl and gplv2 are for licenses

**Comment by kamronbatman** [comment]
Hey Nerun, nice to see you again! Are you on discord? You should join up the new [discord](https://discord.com/invite/7rkM6T7Uq6) and say hi.
