### ISSUE TITLE
Mind Blast Pre AOS Calculation

### ISSUE THREAD

**Issue by greeduomacro** [runuo/runuo#5]
Pretty simple bug here, Mind Blast is being divided by four and it should be divided by 2 in Pre AOS.

Change this in Mindblast.cs:

double damage = this.GetDamageScalar(m) * (highestStat - lowestStat) / 4;//less damage

to this

double damage = this.GetDamageScalar(m) * (highestStat - lowestStat) / 2;//less damage

**Comment by greeduomacro** [comment]
More info here: http://www.playuo.org/emu/index.php?threads/mind-blast-pre-aos-calculation.1011/#post-7538

**Comment by msturgill** [comment]
We've gone back and forth on this one (you'll see 2 is even commented out in the source code). Most places document the modifier as 50%, but many users seem to find that overpowered.

**Comment by greeduomacro** [comment]
Ah yeah, makes sense. =]
